---
# a unix path-friendly name (IE, no spaces or special characters)
project_name: django_polls

# the base path to install to. You should not need to change this.
install_root: /srv

# the python module path to your project's wsgi file. E.g. for a directory
# layout like this (assuming `django_polls` is the project_name and top level
# directory name):
# django_polls
# ├── django_polls
# │   ├── asgi.py
# │   ├── settings.py
# │   ├── urls.py
# │   ├── wsgi.py
# ├── polls
# │   ├── apps
# │   ├── __init__.py
# │   ├── migrations/
# │   ├── static/
# │   ├── templates/
# │   ├── admin.py
# │   ├── apps.py
# │   ├── tests.py
# │   ├── urls.py
# │   ├── views.py
# │   └── models.py
# └── manage.py
# the correct wsgi_module value would be `django_polls.wsgi`
wsgi_module: django_polls.wsgi

# any directories that need to be added to the PYTHONPATH.
pythonpath: "/usr/bin/python3"

# the git repository URL for the project
project_repo: git@github.com:aliciapj/django_polls.git
    
# a private key that has access to the repository URL
ssh_private_key: ~/.ssh/id_rsa

# The value of your django project's STATIC_ROOT settings.
# This will be the directory that django's `collectstatic` management command
# copies static files to, and it must be an absolute path. The default value 
# here assumes that STATIC_ROOT is set in your settings.py like so:
# STATIC_ROOT = os.path.abspath(os.path.join(BASE_DIR, 'static'))
static_root: "{{ install_root }}/{{ project_name }}/polls/static"

# the dns name or names (space separated) for your server
server_name: django-polls.com www.django-polls.com


# apt packages, you should not need to change this unless you have packages
# listed in your requirements.txt that depend on system packages.
system_packages:
  - git
  - nginx
  - gunicorn3
  - python3-pip
  - python3-dev
  - supervisor

# vim:ft=ansible:
